// This file is generated by Sapper — do not edit it!
export const routes = [
	
];

if (module.hot) {
	import('/Users/uk34755246/projects/JoshsBlog/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}